-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.client
(
    client_id BIGSERIAL, -- Auto incrementing primary key
    client_first_name TEXT NOT NULL,
    client_last_name TEXT NOT NULL,
    client_email_address TEXT NOT NULL,
    organizaton_id BIGINT,
    CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public.organization
(
    organization_id BIGSERIAL, -- Auto incrementing primary key
    organization_name TEXT NOT NULL,
    CONSTRAINT organizations_pkey PRIMARY KEY (organization_id)
);

CREATE TABLE IF NOT EXISTS public.provider
(
    provider_id BIGSERIAL, -- Auto incrementing primary key
    provider_first_name TEXT NOT NULL,
    provider_last_name TEXT NOT NULL,
    provider_email_address TEXT NOT NULL,
    organization_id BIGINT,
    CONSTRAINT providers_pkey PRIMARY KEY (provider_id)
);

CREATE TABLE IF NOT EXISTS public.form
(
    form_id BIGSERIAL, -- Auto incrementing primary key
    form_title TEXT NOT NULL,
    form_description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted boolean NOT NULL DEFAULT false,
    organization_id BIGINT NOT NULL,
    CONSTRAINT forms_pkey PRIMARY KEY (form_id)
);

CREATE TABLE IF NOT EXISTS public.form_modification
(
    form_modification_id BIGSERIAL, -- Auto incrementing primary key
    form_modification_type TEXT NOT NULL,
    form_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT form_events_pkey PRIMARY KEY (form_modification_type)
);

CREATE TABLE IF NOT EXISTS public.form_field
(
    form_field_id BIGSERIAL, -- Auto incrementing primary key 
    form_field_title TEXT NOT NULL,
    form_field_description TEXT,
    form_field_options JSONB, 
    form_field_order INTEGER,
    form_field_template_id BIGINT NOT NULL,
    form_id BIGINT NOT NULL,
    CONSTRAINT form_elements_pkey PRIMARY KEY (form_field_id)
);

CREATE TABLE IF NOT EXISTS public.form_field_template
(
    form_field_template_id  BIGSERIAL, -- Auto incrementing primary key
    form_field_template_type TEXT NOT NULL,
    CONSTRAINT form_field_templates_pkey PRIMARY KEY (form_field_template_id)
);

CREATE TABLE IF NOT EXISTS public.form_submission
(
    form_submission_id BIGSERIAL, -- Auto incrementing primary key
    form_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    form_submission_data JSONB NOT NULL, -- Wtih some research, I would do something more performant
    created_at TIMESTAMPTZ,
    CONSTRAINT form_submissions_pkey PRIMARY KEY (form_submission_id)
); 

-- FOREIGN KEYS
ALTER TABLE IF EXISTS public.client
    ADD CONSTRAINT org_fkey FOREIGN KEY (organizaton_id)
    REFERENCES public.organization (organization_id);


ALTER TABLE IF EXISTS public.form
    ADD CONSTRAINT org_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organization (organization_id);


ALTER TABLE IF EXISTS public.form_modification
    ADD CONSTRAINT form_admin_events_form_id_fkey FOREIGN KEY (form_id)
    REFERENCES public.form (form_id);


ALTER TABLE IF EXISTS public.form_modification
    ADD CONSTRAINT form_admin_events_provider_id_fkey FOREIGN KEY (provider_id)
    REFERENCES public.provider (provider_id);


ALTER TABLE IF EXISTS public.form_field
    ADD CONSTRAINT field_template_id_fkey FOREIGN KEY (form_field_template_id)
    REFERENCES public.form_field_template (form_field_template_id);


ALTER TABLE IF EXISTS public.form_field
    ADD CONSTRAINT form_id_fkey FOREIGN KEY (form_id)
    REFERENCES public.form (form_id);


ALTER TABLE IF EXISTS public.form_submission
    ADD CONSTRAINT client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.client (client_id);


ALTER TABLE IF EXISTS public.form_submission
    ADD CONSTRAINT form_id_fkey FOREIGN KEY (form_id)
    REFERENCES public.form (form_id);


ALTER TABLE IF EXISTS public.provider
    ADD CONSTRAINT org_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organization (organization_id);
 
END;